### ISSUE TITLE
Adapter does not start properly

### ISSUE THREAD

**Issue by AlphaLima** [TA2k/ioBroker.weishaupt-wem#11]
The Adapter stays red, no Objects are updated, see error log below.
System running on a Pine Rock64 (Armbian stretch)
npm 6.14.4
nodejs v14.18.2
Any hints, or is it just outdated?

host.ioBroker-Rock64	2021-12-06 08:41:50.198	error	instance system.adapter.weishaupt-wem.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker-Rock64	2021-12-06 08:41:50.197	error	Caught by controller[0]: }
host.ioBroker-Rock64	2021-12-06 08:41:50.196	error	Caught by controller[0]: code: 'ERR_DLOPEN_FAILED'
host.ioBroker-Rock64	2021-12-06 08:41:50.195	error	Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
host.ioBroker-Rock64	2021-12-06 08:41:50.195	error	Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:950:32)
host.ioBroker-Rock64	2021-12-06 08:41:50.194	error	Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
host.ioBroker-Rock64	2021-12-06 08:41:50.193	error	Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1085:14)
host.ioBroker-Rock64	2021-12-06 08:41:50.193	error	Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/canvas/lib/bindings.js:3:18)
host.ioBroker-Rock64	2021-12-06 08:41:50.192	error	Caught by controller[0]: at require (internal/modules/cjs/helpers.js:93:18)
host.ioBroker-Rock64	2021-12-06 08:41:50.191	error	Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:974:19)
host.ioBroker-Rock64	2021-12-06 08:41:50.190	error	Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:790:12)
host.ioBroker-Rock64	2021-12-06 08:41:50.189	error	Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:950:32)
host.ioBroker-Rock64	2021-12-06 08:41:50.189	error	Caught by controller[0]: at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
host.ioBroker-Rock64	2021-12-06 08:41:50.188	error	Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.ioBroker-Rock64	2021-12-06 08:41:50.187	error	Caught by controller[0]: NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
host.ioBroker-Rock64	2021-12-06 08:41:50.186	error	Caught by controller[0]: NODE_MODULE_VERSION 72. This version of Node.js requires
host.ioBroker-Rock64	2021-12-06 08:41:50.185	error	Caught by controller[0]: was compiled against a different Node.js version using
host.ioBroker-Rock64	2021-12-06 08:41:50.183	error	Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/canvas/build/Release/canvas.node'
host.ioBroker-Rock64	2021-12-06 08:41:50.182	error	Caught by controller[0]: ^
host.ioBroker-Rock64	2021-12-06 08:41:50.180	error	Caught by controller[0]: return process.dlopen(module, path.toNamespacedPath(filename));
host.ioBroker-Rock64	2021-12-06 08:41:50.179	error	Caught by controller[0]: internal/modules/cjs/loader.js:1144

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by TA2k** [comment]
Please follow the nodejs update guidleine and rebuild the packages with npm rebuild

**Comment by AlphaLima** [comment]
did that already, that didn't change anything.

**Comment by TA2k** [comment]
`cd /opt/iobroker
npm install
npm rebuild`

oder halt adapter löschen und neuinstallieren

**Comment by AlphaLima** [comment]
Nee, bringt leider nichts, auf einer ioBroker Installation auf dem PC läuft der Adapter. Kann das am Rock64 liegen?


<html>
<body>


host.ioBroker-Rock64 | 2021-12-06 18:16:14.994 | info | Rebuild for adapter system.adapter.weishaupt-wem.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.
-- | -- | -- | --
host.ioBroker-Rock64 | 2021-12-06 18:16:14.993 | error | instance system.adapter.weishaupt-wem.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker-Rock64 | 2021-12-06 18:16:14.993 | error | Caught by controller[0]: }
host.ioBroker-Rock64 | 2021-12-06 18:16:14.992 | error | Caught by controller[0]: code: 'ERR_DLOPEN_FAILED'
host.ioBroker-Rock64 | 2021-12-06 18:16:14.992 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
host.ioBroker-Rock64 | 2021-12-06 18:16:14.991 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:950:32)
host.ioBroker-Rock64 | 2021-12-06 18:16:14.991 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
host.ioBroker-Rock64 | 2021-12-06 18:16:14.990 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1085:14)
host.ioBroker-Rock64 | 2021-12-06 18:16:14.989 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/canvas/lib/bindings.js:3:18)
host.ioBroker-Rock64 | 2021-12-06 18:16:14.989 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:93:18)
host.ioBroker-Rock64 | 2021-12-06 18:16:14.988 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:974:19)
host.ioBroker-Rock64 | 2021-12-06 18:16:14.988 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:790:12)
host.ioBroker-Rock64 | 2021-12-06 18:16:14.987 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:950:32)
host.ioBroker-Rock64 | 2021-12-06 18:16:14.987 | error | Caught by controller[0]: at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
host.ioBroker-Rock64 | 2021-12-06 18:16:14.986 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.ioBroker-Rock64 | 2021-12-06 18:16:14.985 | error | Caught by controller[0]: NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
host.ioBroker-Rock64 | 2021-12-06 18:16:14.985 | error | Caught by controller[0]: NODE_MODULE_VERSION 72. This version of Node.js requires
host.ioBroker-Rock64 | 2021-12-06 18:16:14.984 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.ioBroker-Rock64 | 2021-12-06 18:16:14.984 | error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/canvas/build/Release/canvas.node'
host.ioBroker-Rock64 | 2021-12-06 18:16:14.983 | error | Caught by controller[0]: ^
host.ioBroker-Rock64 | 2021-12-06 18:16:14.982 | error | Caught by controller[0]: return process.dlopen(module, path.toNamespacedPath(filename));
host.ioBroker-Rock64 | 2021-12-06 18:16:14.981 | error | Caught by controller[0]: internal/modules/cjs/loader.js:1144
host.ioBroker-Rock64 | 2021-12-06 18:16:11.277 | info | instance system.adapter.weishaupt-wem.0 started with pid 4137
host.ioBroker-Rock64 | 2021-12-06 18:16:10.827 | info | Rebuild for adapter system.adapter.weishaupt-wem.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.
host.ioBroker-Rock64 | 2021-12-06 18:16:10.826 | error | instance system.adapter.weishaupt-wem.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker-Rock64 | 2021-12-06 18:16:10.825 | error | Caught by controller[0]: }
host.ioBroker-Rock64 | 2021-12-06 18:16:10.824 | error | Caught by controller[0]: code: 'ERR_DLOPEN_FAILED'


</body>
</html>

**Comment by TA2k** [comment]
`cd /opt/iobroker 
npm install canvas`

**Comment by AlphaLima** [comment]
Nee funktioniert leider nicht

npm install --production löst das Problem auch nicht.
<html>
<body>


host.ioBroker-Rock64 | 2021-12-06 18:48:15.961 | info | Rebuild for adapter system.adapter.weishaupt-wem.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.
-- | -- | -- | --
host.ioBroker-Rock64 | 2021-12-06 18:48:15.961 | error | instance system.adapter.weishaupt-wem.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker-Rock64 | 2021-12-06 18:48:15.960 | error | Caught by controller[0]: }
host.ioBroker-Rock64 | 2021-12-06 18:48:15.959 | error | Caught by controller[0]: code: 'ERR_DLOPEN_FAILED'
host.ioBroker-Rock64 | 2021-12-06 18:48:15.959 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
host.ioBroker-Rock64 | 2021-12-06 18:48:15.958 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:950:32)
host.ioBroker-Rock64 | 2021-12-06 18:48:15.958 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
host.ioBroker-Rock64 | 2021-12-06 18:48:15.957 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1085:14)
host.ioBroker-Rock64 | 2021-12-06 18:48:15.956 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/canvas/lib/bindings.js:3:18)
host.ioBroker-Rock64 | 2021-12-06 18:48:15.956 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:93:18)
host.ioBroker-Rock64 | 2021-12-06 18:48:15.955 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:974:19)
host.ioBroker-Rock64 | 2021-12-06 18:48:15.955 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:790:12)
host.ioBroker-Rock64 | 2021-12-06 18:48:15.954 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:950:32)
host.ioBroker-Rock64 | 2021-12-06 18:48:15.953 | error | Caught by controller[0]: at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
host.ioBroker-Rock64 | 2021-12-06 18:48:15.953 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.ioBroker-Rock64 | 2021-12-06 18:48:15.952 | error | Caught by controller[0]: NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
host.ioBroker-Rock64 | 2021-12-06 18:48:15.951 | error | Caught by controller[0]: NODE_MODULE_VERSION 72. This version of Node.js requires
host.ioBroker-Rock64 | 2021-12-06 18:48:15.951 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.ioBroker-Rock64 | 2021-12-06 18:48:15.950 | error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/canvas/build/Release/canvas.node'
host.ioBroker-Rock64 | 2021-12-06 18:48:15.950 | error | Caught by controller[0]: ^
host.ioBroker-Rock64 | 2021-12-06 18:48:15.949 | error | Caught by controller[0]: return process.dlopen(module, path.toNamespacedPath(filename));
host.ioBroker-Rock64 | 2021-12-06 18:48:15.948 | error | Caught by controller[0]: internal/modules/cjs/loader.js:1144
host.ioBroker-Rock64 | 2021-12-06 18:48:12.958 | info | instance system.adapter.weishaupt-wem.0 started with pid 5318
host.ioBroker-Rock64 | 2021-12-06 18:47:58.980 | info | iobroker exit 0


</body>
</html>

**Comment by TA2k** [comment]
npm install canvas

oder
iob update

dann sollte ein Update verfügbar sein

**Comment by AlphaLima** [comment]
Das war es leider auch nicht habe dann Node noch mal komplett nach folgender Anleitung installiert, 
https://www.elzershark.com/forum/index.php?thread/110-upgrade-node-xx-xx-z-b-12-x-zu-node-14-x-f%C3%BCr-iobroker/
dann hat es funktioniert.
Trotzdem danke für die schnelle Hilfe!
